### ISSUE TITLE
No version seems to compile with Unreal Engine 4.20.3

### ISSUE THREAD

**Issue by JackRonan** [NegInfinity/ProjectExodus#30]
I realise this is an older version but I cannot get the plugin to compile no matter which version I download. I have Visual Studio 2017 and 2019 installed (wasn't sure if I needed 2015 for some reason) or if there is a particular build that should definitely work?

**Comment by NegInfinity** [comment]
Hello, @JackRonan . The plugin supports 3 latest major releases only. The supported versions are listed in readme file.  Currently those are 4.25.x, 4.24.x, 4.23.x. It was decided to do things this way due to frequent noticeable api changes between releases. The earliest you might be able to compile it on is 4.22, and even that if you're lucky. I don't think there's a github version with 4.20 support.

I would advise to upgrade.

**Comment by JackRonan** [comment]
Ah okay, thank you. The version I had tried to use was one that in the readme at the time stated could compile on 4.19.x but either way, it isn't working. 

I wish I could upgrade but unfortunately I'm trying to port a Unity map to mod a game that requires that specific version of Unreal so it seems I'm stuck. Thanks anyway! The plugin works amazingly on the latest version of Unreal, there's just no easy way to downgrade a project!
